#指定运行环境
language: node_js
#指定nodejs版本，可以指定多个
node_js:
  - 5.10

#运行的脚本命令
script:
  - gulp

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
    
after_success:
    - npm prune --production  # 删除devDependencies
    - tar gulp build   # 打包并压缩代码